packages:
  - "apps/*"
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  workerd: true
